[project]
name = "nautilus-trader-demo-strategies"
version = "0.1.0"
description = "Demo examples of various strategies and features implemented in Nautilus Trader."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nautilus_trader==1.210.0"
]

# Uncomment this only if you need to download alpha/dev versions from custom package index of Nautilus.
# See latest releases: https://packages.nautechsystems.io/simple/nautilus-trader/index.html
# [[tool.uv.index]]
# name = "nautilus_pypi"
# url = "https://packages.nautechsystems.io/simple"

[tool.ruff]
line-length = 30000  # we want to manage line length ourselves
fix = true
show-fixes = true